# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory : hello-world

    steps:
    #- run: npm run build --if-present
    #- run: npm test
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{matrix.node-version}}
    - name: Cache node modules
      id: cache-nodemodules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules # 👈 path for node_modules folder
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Dependencies
      if:
        github.event.pull_request.merged==true 
      run: npm install
    - name: Build
      if: github.event.pull_request.merged==true 
      run: npm run build:prod

  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory : hello-world
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ${{github.repository}}
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
      with:
        github_access_token: ${{ secrets.MYSECRETNAME }} # see the Configuration section for how you can create secrets
        deploy_branch: gh-pages # The branch the action should deploy to.
        angular_dist_build_folder: dist/hello-world/ # The folder where your project is supposed to be after running ng build by the action.
